"""Seed data matching the 12 hardcoded clients in cockpit.html."""

CLIENTS = [
    {"client_id": "ricardo",  "name": "Ricardo Tanaka",    "vip": True,  "risk_profile": "Aggressive",    "aum": 12800000, "aum_currency": "BRL", "equity_pct": 71, "fixed_income_pct": 14, "funds_pct": 10, "cash_pct": 5,  "status": "at_risk",     "client_since": "2018-03-15", "equity_limit": 80},
    {"client_id": "fernando", "name": "Fernando Costa",    "vip": True,  "risk_profile": "Aggressive",    "aum": 23000000, "aum_currency": "BRL", "equity_pct": 71, "fixed_income_pct": 18, "funds_pct": 8,  "cash_pct": 3,  "status": "attention",   "client_since": "2015-07-22", "equity_limit": 80},
    {"client_id": "beatriz",  "name": "Beatriz Oliveira",  "vip": True,  "risk_profile": "Moderate",      "aum": 8500000,  "aum_currency": "BRL", "equity_pct": 42, "fixed_income_pct": 38, "funds_pct": 15, "cash_pct": 5,  "status": "pending",     "client_since": "2020-01-10", "equity_limit": 60},
    {"client_id": "carlos",   "name": "Carlos Mendes",     "vip": False, "risk_profile": "Conservative",  "aum": 3200000,  "aum_currency": "BRL", "equity_pct": 18, "fixed_income_pct": 62, "funds_pct": 12, "cash_pct": 8,  "status": "healthy",     "client_since": "2019-11-05", "equity_limit": 30},
    {"client_id": "ana",      "name": "Ana Souza",         "vip": False, "risk_profile": "Moderate",      "aum": 5600000,  "aum_currency": "BRL", "equity_pct": 35, "fixed_income_pct": 45, "funds_pct": 15, "cash_pct": 5,  "status": "opportunity", "client_since": "2021-06-18", "equity_limit": 60},
    {"client_id": "pedro",    "name": "Pedro Alves",       "vip": False, "risk_profile": "Aggressive",    "aum": 7100000,  "aum_currency": "BRL", "equity_pct": 58, "fixed_income_pct": 22, "funds_pct": 14, "cash_pct": 6,  "status": "healthy",     "client_since": "2017-09-30", "equity_limit": 80},
    {"client_id": "lucia",    "name": "Lúcia Fernandes",   "vip": True,  "risk_profile": "Conservative",  "aum": 15400000, "aum_currency": "BRL", "equity_pct": 22, "fixed_income_pct": 58, "funds_pct": 12, "cash_pct": 8,  "status": "awaiting",    "client_since": "2014-04-12", "equity_limit": 30},
    {"client_id": "roberto",  "name": "Roberto Lima",      "vip": False, "risk_profile": "Moderate",      "aum": 4300000,  "aum_currency": "BRL", "equity_pct": 48, "fixed_income_pct": 32, "funds_pct": 12, "cash_pct": 8,  "status": "at_risk",     "client_since": "2022-02-28", "equity_limit": 60},
    {"client_id": "mariana",  "name": "Mariana Castro",    "vip": False, "risk_profile": "Aggressive",    "aum": 6800000,  "aum_currency": "BRL", "equity_pct": 65, "fixed_income_pct": 20, "funds_pct": 10, "cash_pct": 5,  "status": "opportunity", "client_since": "2020-08-14", "equity_limit": 80},
    {"client_id": "paulo",    "name": "Paulo Rodrigues",   "vip": False, "risk_profile": "Conservative",  "aum": 2900000,  "aum_currency": "BRL", "equity_pct": 15, "fixed_income_pct": 70, "funds_pct": 10, "cash_pct": 5,  "status": "healthy",     "client_since": "2023-01-20", "equity_limit": 30},
    {"client_id": "camila",   "name": "Camila Pereira",    "vip": False, "risk_profile": "Moderate",      "aum": 4100000,  "aum_currency": "BRL", "equity_pct": 40, "fixed_income_pct": 40, "funds_pct": 15, "cash_pct": 5,  "status": "pending",     "client_since": "2021-11-03", "equity_limit": 60},
    {"client_id": "andre",    "name": "André Barbosa",     "vip": True,  "risk_profile": "Aggressive",    "aum": 19200000, "aum_currency": "BRL", "equity_pct": 74, "fixed_income_pct": 16, "funds_pct": 7,  "cash_pct": 3,  "status": "at_risk",     "client_since": "2016-05-25", "equity_limit": 80},
]
