"""Conversation seed data for all 12 clients — SPEC-008."""

CONVERSATIONS = [
    # ── RICARDO TANAKA ────────────────────────────────────────────────────────
    {"conv_id":"conv-ricardo-20260614","client_id":"ricardo","channel":"call","conv_date":"2026-06-14","duration_s":512,"sentiment":"negative","has_audio":True,"audio_file":"ricardo_20260614.mp3",
     "summary_en":"Ricardo alarmed by market volatility, baby arriving in 3 months. Wants to cut equity 71%→55% and build 12-month emergency reserve. Agreed on written plan.",
     "summary_pt":"Ricardo alarmado com volatilidade, bebê chegando em 3 meses. Quer reduzir RV de 71% para 55% e montar reserva de emergência de 12 meses. Concordou com plano por escrito."},
    {"conv_id":"conv-ricardo-20260609","client_id":"ricardo","channel":"whatsapp","conv_date":"2026-06-09","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Ricardo worried about intraday IBOVESPA flash drop (-1.8%). Advisor reassures: portfolio within limits, review call scheduled Jun 14.",
     "summary_pt":"Ricardo preocupado com queda intraday do Ibovespa (-1,8%). Assessor tranquiliza: carteira dentro dos limites, call de revisão agendada para 14/jun."},
    {"conv_id":"conv-ricardo-20260528","client_id":"ricardo","channel":"call","conv_date":"2026-05-28","duration_s":735,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Q2 routine review. Portfolio +2.3% YTD. Ricardo first mentions baby coming — signals future risk aversion shift. No action yet.",
     "summary_pt":"Revisão de rotina Q2. Carteira +2,3% no ano. Ricardo menciona pela primeira vez o bebê chegando — sinal de mudança de perfil. Sem ação ainda."},
    {"conv_id":"conv-ricardo-20260515","client_id":"ricardo","channel":"email","conv_date":"2026-05-15","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Advisor sent updated suitability questionnaire. Ricardo's responses show lower risk tolerance than current aggressive profile. Profile change assessment flagged.",
     "summary_pt":"Assessor enviou questionário de suitability atualizado. Respostas de Ricardo indicam tolerância a risco menor que o perfil arrojado atual. Avaliação de mudança de perfil sinalizada."},
    {"conv_id":"conv-ricardo-20260430","client_id":"ricardo","channel":"call","conv_date":"2026-04-30","duration_s":543,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Ricardo happy with Q1 +8.2% returns. Asked about increasing equity exposure. Advisor cautioned: already at 71%, near policy band. Last conversation before risk signal.",
     "summary_pt":"Ricardo feliz com retorno de +8,2% no Q1. Pediu para aumentar exposição em RV. Assessor alertou: já em 71%, próximo da banda. Última conversa antes do sinal de risco."},

    # ── FERNANDO COSTA ────────────────────────────────────────────────────────
    {"conv_id":"conv-fernando-20260610","client_id":"fernando","channel":"call","conv_date":"2026-06-10","duration_s":724,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Compliance flag triggered: equity at 71% above 60% policy band. Fernando refuses to reduce. Advisor documents formally. Fernando agrees to 'review' only.",
     "summary_pt":"Alerta de compliance: RV em 71%, acima da banda de 60%. Fernando recusa redução. Assessor documenta formalmente. Fernando concorda apenas em 'revisar'."},
    {"conv_id":"conv-fernando-20260605","client_id":"fernando","channel":"whatsapp","conv_date":"2026-06-05","duration_s":None,"sentiment":"negative","has_audio":False,"audio_file":None,
     "summary_en":"Fernando wants to add R$500k in tech equities (would push to 74%). Advisor declines citing policy, proposes multimarket alternative. Fernando reluctant.",
     "summary_pt":"Fernando quer adicionar R$500k em ações de tech (subiria para 74%). Assessor recusa por política, propõe alternativa em multimercado. Fernando relutante."},
    {"conv_id":"conv-fernando-20260520","client_id":"fernando","channel":"call","conv_date":"2026-05-20","duration_s":618,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Second compliance review — equity still at 71% after 6 weeks. Portfolio committee formally notified. Fernando given two options: trim or file exception.",
     "summary_pt":"Segunda revisão de compliance — RV ainda em 71% após 6 semanas. Comitê de carteira formalmente notificado. Fernando recebe duas opções: reduzir ou solicitar exceção."},
    {"conv_id":"conv-fernando-20260510","client_id":"fernando","channel":"email","conv_date":"2026-05-10","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Q1 portfolio drift report: equity drifted from agreed 60% to 68% during bull market. First formal documentation of the breach. Rebalancing proposal sent.",
     "summary_pt":"Relatório de drift Q1: RV passou de 60% acordado para 68% durante bull market. Primeira documentação formal da violação. Proposta de rebalanceamento enviada."},
    {"conv_id":"conv-fernando-20260425","client_id":"fernando","channel":"call","conv_date":"2026-04-25","duration_s":812,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Fernando wants to liquidate all fixed income and go 100% equities after strong Q1. Advisor negotiates to 71% max. This conversation established the current concentration.",
     "summary_pt":"Fernando quer liquidar toda a renda fixa e ir 100% em RV após Q1 forte. Assessor negocia teto de 71%. Conversa que originou a concentração atual."},

    # ── HELENA VASCONCELOS ────────────────────────────────────────────────────
    {"conv_id":"conv-helena-20260612","client_id":"helena","channel":"whatsapp","conv_date":"2026-06-12","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Helena reviewing reallocation proposal (10% RF → multimarket, CDI+1.8% projected). Says she will have an answer by Friday.",
     "summary_pt":"Helena revisando proposta de realocação (10% RF → multimercado, projeção CDI+1,8%). Diz que terá resposta até sexta."},
    {"conv_id":"conv-helena-20260608","client_id":"helena","channel":"email","conv_date":"2026-06-08","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Advisor sent detailed reallocation proposal. Current: 100% fixed income yielding CDI+0.9%. Proposed: 10% multimarket, projecting blended CDI+1.4%.",
     "summary_pt":"Assessor enviou proposta detalhada de realocação. Atual: 100% RF com CDI+0,9%. Proposta: 10% multimercado, projeção blended de CDI+1,4%."},
    {"conv_id":"conv-helena-20260530","client_id":"helena","channel":"call","conv_date":"2026-05-30","duration_s":927,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Helena asks for deep-dive on multimarket funds. Advisor explains structure, historical performance, liquidity. Helena warming to the idea, wants to consult accountant.",
     "summary_pt":"Helena pede explicação detalhada sobre fundos multimercado. Assessor explica estrutura, histórico e liquidez. Helena mais receptiva, quer consultar contador."},
    {"conv_id":"conv-helena-20260522","client_id":"helena","channel":"whatsapp","conv_date":"2026-05-22","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Helena asks about May MTD performance. Advisor: +0.4%, in line with CDI. Helena satisfied, mentions she may be open to 'something slightly better.'",
     "summary_pt":"Helena pergunta sobre retorno no mês. Assessor: +0,4%, em linha com CDI. Helena satisfeita, menciona que pode estar aberta a 'algo um pouco melhor'."},
    {"conv_id":"conv-helena-20260515","client_id":"helena","channel":"call","conv_date":"2026-05-15","duration_s":3300,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Annual review — 5 years as client. Helena satisfied but notes compressed real returns on fixed income. Advisor identifies multimarket opportunity. Proposal follow-up scheduled.",
     "summary_pt":"Revisão anual — 5 anos como cliente. Helena satisfeita mas nota retornos reais comprimidos na RF. Assessor identifica oportunidade em multimercado. Follow-up de proposta agendado."},

    # ── OTÁVIO MENDES ─────────────────────────────────────────────────────────
    {"conv_id":"conv-otavio-20260609","client_id":"otavio","channel":"call","conv_date":"2026-06-09","duration_s":378,"sentiment":"positive","has_audio":True,"audio_file":"otavio_20260609.mp3",
     "summary_en":"Otávio confirms R$500k inflow on July 15. Advisor proposes: 50% equities, 30% infra credit fund (CDI+3.2%), 20% multimarket. Otávio approves, asks for written plan.",
     "summary_pt":"Otávio confirma aporte de R$500k em 15 de julho. Assessor propõe: 50% RV, 30% fundo de infra (CDI+3,2%), 20% multimercado. Otávio aprova, pede plano por escrito."},
    {"conv_id":"conv-otavio-20260602","client_id":"otavio","channel":"whatsapp","conv_date":"2026-06-02","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Otávio confirms inflow date (July 15, R$500k) and asks about the infrastructure fund subscription window (closes Jun 30).",
     "summary_pt":"Otávio confirma data do aporte (15 de julho, R$500k) e pergunta sobre janela de subscrição do fundo de infra (fecha 30 de junho)."},
    {"conv_id":"conv-otavio-20260528","client_id":"otavio","channel":"call","conv_date":"2026-05-28","duration_s":547,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Advisor proactively calls about new infra credit fund (CDI+3.2%, window closes Jun 30). Otávio very interested, decides to wait for July inflow for full allocation.",
     "summary_pt":"Assessor liga proativamente sobre novo fundo de crédito de infra (CDI+3,2%, janela fecha 30 jun). Otávio muito interessado, decide esperar aporte de julho para alocação completa."},
    {"conv_id":"conv-otavio-20260520","client_id":"otavio","channel":"whatsapp","conv_date":"2026-05-20","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Otávio received R$28k in dividends. Asks whether to reinvest or keep as cash. Advisor recommends reinvesting in fixed income sleeve given current yield curve.",
     "summary_pt":"Otávio recebeu R$28k em dividendos. Pergunta se reinveste ou mantém caixa. Assessor recomenda reinvestir na parcela de renda fixa dado o patamar atual da curva."},
    {"conv_id":"conv-otavio-20260510","client_id":"otavio","channel":"call","conv_date":"2026-05-10","duration_s":840,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Q2 review — portfolio at R$7.6M, up +2.3%. Otávio very happy. Discusses Q3 strategy and first mentions upcoming July inflow. Strong client relationship.",
     "summary_pt":"Revisão Q2 — carteira em R$7,6M, alta de +2,3%. Otávio muito satisfeito. Discute estratégia Q3 e menciona pela primeira vez o aporte de julho. Relacionamento sólido."},

    # ── BEATRIZ ALMEIDA ───────────────────────────────────────────────────────
    {"conv_id":"conv-beatriz-20260611","client_id":"beatriz","channel":"email","conv_date":"2026-06-11","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Urgent notice: suitability assessment expires Jun 30 (19 days). Trading and rebalancing blocked until renewed. Advisor requests appointment before deadline.",
     "summary_pt":"Aviso urgente: suitability vence em 30 de junho (19 dias). Negociações e rebalanceamento bloqueados até renovação. Assessor solicita agendamento antes do prazo."},
    {"conv_id":"conv-beatriz-20260607","client_id":"beatriz","channel":"whatsapp","conv_date":"2026-06-07","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Beatriz asks to schedule suitability renewal. Limited availability due to school exam period. Tentatively set for Jun 25.",
     "summary_pt":"Beatriz pede para agendar renovação de suitability. Disponibilidade limitada pela época de provas na escola. Provisoriamente marcado para 25 de junho."},
    {"conv_id":"conv-beatriz-20260528","client_id":"beatriz","channel":"call","conv_date":"2026-05-28","duration_s":1623,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Beatriz questions whether conservative profile makes sense given compressed real returns. Advisor explains retirement timeline rationale (2 years). Beatriz confirms conservative profile.",
     "summary_pt":"Beatriz questiona se perfil conservador faz sentido dado retornos reais comprimidos. Assessor explica racional do horizonte de aposentadoria (2 anos). Beatriz confirma perfil conservador."},
    {"conv_id":"conv-beatriz-20260520","client_id":"beatriz","channel":"whatsapp","conv_date":"2026-05-20","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Beatriz asks about YTD returns. Advisor: +3.4%, CDI-aligned. On track for R$2M retirement target if contributions continue.",
     "summary_pt":"Beatriz pergunta sobre retorno no ano. Assessor: +3,4%, em linha com CDI. No caminho para meta de aposentadoria de R$2M se contribuições continuarem."},
    {"conv_id":"conv-beatriz-20260510","client_id":"beatriz","channel":"call","conv_date":"2026-05-10","duration_s":1980,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Formal retirement planning analysis — 2 years out. With R$1.5M today and continued contributions, Beatriz reaches her retirement target. Retirement date goal formalized.",
     "summary_pt":"Análise formal de planejamento de aposentadoria — 2 anos para a data. Com R$1,5M hoje e contribuições contínuas, Beatriz atinge a meta. Data de aposentadoria formalizada."},

    # ── LÚCIA PRADO ───────────────────────────────────────────────────────────
    {"conv_id":"conv-lucia-20260608","client_id":"lucia","channel":"whatsapp","conv_date":"2026-06-08","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Lúcia sees May statement, very happy with +0.9% for the month. Advisor notes birthday coming up. Opens door for pension cross-sell call.",
     "summary_pt":"Lúcia vê extrato de maio, muito feliz com +0,9% no mês. Assessor anota aniversário chegando. Abre espaço para ligação sobre previdência."},
    {"conv_id":"conv-lucia-20260603","client_id":"lucia","channel":"call","conv_date":"2026-06-03","duration_s":1382,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Lúcia proactively asks about PGBL pension plans. Advisor explains: 12% gross income deduction, ideal for 27.5% tax bracket. Projects R$18k/year tax savings with R$65k annual contribution.",
     "summary_pt":"Lúcia pergunta proativamente sobre previdência PGBL. Assessor explica: dedução de 12% da renda bruta, ideal para faixa de 27,5%. Projeta economia de R$18k/ano com contribuição anual de R$65k."},
    {"conv_id":"conv-lucia-20260528","client_id":"lucia","channel":"email","conv_date":"2026-05-28","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Monthly report May sent. Portfolio at R$3.1M, YTD +4.2%. No action needed. Lúcia replies with a grateful emoji.",
     "summary_pt":"Relatório mensal de maio enviado. Carteira em R$3,1M, +4,2% no ano. Sem ação necessária. Lúcia responde com emoji de agradecimento."},
    {"conv_id":"conv-lucia-20260520","client_id":"lucia","channel":"whatsapp","conv_date":"2026-05-20","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Lúcia asks about withdrawing R$50k for a business investment. Advisor discusses impact (1.6% of total) and tax implications. Lúcia decides to proceed.",
     "summary_pt":"Lúcia pergunta sobre resgatar R$50k para investimento no negócio. Assessor discute impacto (1,6% do total) e implicações fiscais. Lúcia decide prosseguir."},
    {"conv_id":"conv-lucia-20260510","client_id":"lucia","channel":"call","conv_date":"2026-05-10","duration_s":1830,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Q1 review. Lúcia happy with +3.3% YTD. First formal mention of interest in a pension plan. Advisor notes as opportunity to follow up in coming months.",
     "summary_pt":"Revisão Q1. Lúcia satisfeita com +3,3% no ano. Primeira menção formal de interesse em previdência. Assessor registra como oportunidade para follow-up nos próximos meses."},

    # ── GUSTAVO REIS ─────────────────────────────────────────────────────────
    {"conv_id":"conv-gustavo-20260613","client_id":"gustavo","channel":"call","conv_date":"2026-06-13","duration_s":581,"sentiment":"negative","has_audio":False,"audio_file":None,
     "summary_en":"Investment committee rejected rebalance proposal. Portfolio stuck at 68% equity, above limit. Advisor documents second compliance event. Two paths: committee appeal or sub-R$1M workaround.",
     "summary_pt":"Comitê de investimentos rejeitou proposta de rebalanceamento. Carteira travada em 68% de RV, acima do limite. Assessor documenta segundo evento de compliance. Dois caminhos: recurso ou alternativa abaixo de R$1M."},
    {"conv_id":"conv-gustavo-20260607","client_id":"gustavo","channel":"whatsapp","conv_date":"2026-06-07","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Gustavo asks if there's an alternative to the committee process. Advisor outlines 3 options: wait, file exemption, or partial rebalance under R$1M threshold.",
     "summary_pt":"Gustavo pergunta se há alternativa ao processo do comitê. Assessor apresenta 3 opções: aguardar, solicitar isenção, ou rebalanceamento parcial abaixo de R$1M."},
    {"conv_id":"conv-gustavo-20260530","client_id":"gustavo","channel":"call","conv_date":"2026-05-30","duration_s":840,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Gustavo interested in adding LatAm equity exposure. Advisor recommends waiting for current rebalance approval first. Gustavo reluctantly agrees to delay.",
     "summary_pt":"Gustavo interessado em adicionar exposição a ações LatAm. Assessor recomenda aguardar aprovação do rebalanceamento atual primeiro. Gustavo concorda relutantemente."},
    {"conv_id":"conv-gustavo-20260522","client_id":"gustavo","channel":"email","conv_date":"2026-05-22","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Rebalancing proposal v2 submitted to investment committee — reduced scope from R$2.4M to R$900k (below the R$1M full-vote threshold). Awaiting response.",
     "summary_pt":"Proposta de rebalanceamento v2 enviada ao comitê — escopo reduzido de R$2,4M para R$900k (abaixo do limite de R$1M que exige voto pleno). Aguardando resposta."},
    {"conv_id":"conv-gustavo-20260515","client_id":"gustavo","channel":"call","conv_date":"2026-05-15","duration_s":3600,"sentiment":"negative","has_audio":False,"audio_file":None,
     "summary_en":"Q2 review — portfolio down 2.9% vs index -1.8%. Concentrated international equity underperformed. First discussion of the governance constraint on rebalancing.",
     "summary_pt":"Revisão Q2 — carteira caiu 2,9% vs índice -1,8%. Posição concentrada em RV internacional com desempenho inferior. Primeira discussão sobre restrição de governança no rebalanceamento."},

    # ── ANDRÉ LIMA ────────────────────────────────────────────────────────────
    {"conv_id":"conv-andre-20260613","client_id":"andre","channel":"call","conv_date":"2026-06-13","duration_s":687,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"André acknowledges equity drift to 62% (vs 60% policy max). Wants to wait for market recovery before trimming. Advisor formally documents second policy breach.",
     "summary_pt":"André reconhece drift da RV para 62% (vs máximo de 60% na política). Quer aguardar recuperação do mercado antes de reduzir. Assessor documenta formalmente segundo evento de violação."},
    {"conv_id":"conv-andre-20260607","client_id":"andre","channel":"whatsapp","conv_date":"2026-06-07","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"André asks to confirm his current equity policy band. Advisor confirms 60% max, currently at 62%. Suggests R$150k trim to come within band. André will decide next week.",
     "summary_pt":"André pede confirmação da sua banda de política de RV. Assessor confirma: máximo 60%, atualmente em 62%. Sugere redução de R$150k para voltar à banda. André decidirá na semana seguinte."},
    {"conv_id":"conv-andre-20260528","client_id":"andre","channel":"call","conv_date":"2026-05-28","duration_s":813,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"André asks about participating in a fintech IPO. Advisor declines: would push equity from 62% to ~65%, worsening the policy breach. André disappointed but understands.",
     "summary_pt":"André pergunta sobre participar de IPO de fintech. Assessor recusa: elevaria RV de 62% para ~65%, agravando a violação de política. André desapontado mas compreende."},
    {"conv_id":"conv-andre-20260520","client_id":"andre","channel":"email","conv_date":"2026-05-20","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Formal written notification: equity allocation exceeded approved band by 2pp for 45 consecutive days. André acknowledges and states he will 'address it in Q3.'",
     "summary_pt":"Notificação formal por escrito: alocação em RV ultrapassou banda aprovada em 2pp por 45 dias consecutivos. André reconhece e diz que vai 'resolver no Q3'."},
    {"conv_id":"conv-andre-20260510","client_id":"andre","channel":"call","conv_date":"2026-05-10","duration_s":3240,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Annual review. 5-year CAGR +12.4% vs Ibovespa +8.9%. André satisfied long-term. Current quarter challenging (-1.8%). Equity drift to 62% originated in Q1 bull market run.",
     "summary_pt":"Revisão anual. CAGR de 5 anos +12,4% vs Ibovespa +8,9%. André satisfeito no longo prazo. Trimestre atual desafiador (-1,8%). Drift da RV para 62% originou-se no bull market do Q1."},

    # ── CAMILA REZENDE ────────────────────────────────────────────────────────
    {"conv_id":"conv-camila-20260609","client_id":"camila","channel":"whatsapp","conv_date":"2026-06-09","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Camila still thinking about migrating VGBL → PGBL pension. Spoke with accountant. Awaiting final decision on the tax arbitrage opportunity.",
     "summary_pt":"Camila ainda pensando sobre migração VGBL → PGBL. Conversou com contador. Aguardando decisão final sobre a arbitragem fiscal."},
    {"conv_id":"conv-camila-20260603","client_id":"camila","channel":"email","conv_date":"2026-06-03","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Updated migration analysis sent: PGBL saves R$6.4k/year in income tax. Net benefit over 10 years: R$84k. Camila wants a second opinion before deciding.",
     "summary_pt":"Análise atualizada de migração enviada: PGBL economiza R$6,4k/ano em IR. Benefício líquido em 10 anos: R$84k. Camila quer segunda opinião antes de decidir."},
    {"conv_id":"conv-camila-20260525","client_id":"camila","channel":"call","conv_date":"2026-05-25","duration_s":1980,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Camila worried about liquidity during pension migration. Advisor explains 60-day transition with full access to funds throughout. Camila more comfortable.",
     "summary_pt":"Camila preocupada com liquidez durante a migração de previdência. Assessor explica transição de 60 dias com acesso total aos recursos. Camila fica mais confortável."},
    {"conv_id":"conv-camila-20260515","client_id":"camila","channel":"whatsapp","conv_date":"2026-05-15","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Camila asks if there's a tax year deadline for the PGBL benefit. Advisor confirms: must be enrolled before Dec 31 to claim 2026 deduction. Creates urgency.",
     "summary_pt":"Camila pergunta se há prazo do ano fiscal para o benefício PGBL. Assessor confirma: precisa estar inscrita antes de 31/dez para aproveitar dedução de 2026. Cria urgência."},
    {"conv_id":"conv-camila-20260505","client_id":"camila","channel":"call","conv_date":"2026-05-05","duration_s":2520,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Initial pension migration conversation. Camila was on VGBL with another provider. Advisor identifies tax arbitrage (PGBL deduction) and proposes migration to the platform.",
     "summary_pt":"Conversa inicial sobre migração de previdência. Camila estava em VGBL com outro provedor. Assessor identifica arbitragem fiscal (dedução PGBL) e propõe migração para a plataforma."},

    # ── PAULO ESTEVES ─────────────────────────────────────────────────────────
    {"conv_id":"conv-paulo-20260618","client_id":"paulo","channel":"email","conv_date":"2026-06-18","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Q2 check-in. Portfolio +3.6% YTD, ahead of blended benchmark. No action required. Paulo confirms everything is fine.",
     "summary_pt":"Check-in Q2. Carteira +3,6% no ano, acima do benchmark blended. Sem ação necessária. Paulo confirma que está tudo bem."},
    {"conv_id":"conv-paulo-20260605","client_id":"paulo","channel":"whatsapp","conv_date":"2026-06-05","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Dividend of R$12k received and auto-reinvested per standing instruction. Paulo confirms he saw the notification.",
     "summary_pt":"Dividendo de R$12k recebido e reinvestido automaticamente conforme instrução permanente. Paulo confirma que viu a notificação."},
    {"conv_id":"conv-paulo-20260520","client_id":"paulo","channel":"call","conv_date":"2026-05-20","duration_s":2460,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Annual review. +3.6% YTD vs blended benchmark. No changes requested. Q3 review scheduled for July.",
     "summary_pt":"Revisão anual. +3,6% no ano vs benchmark blended. Sem alterações solicitadas. Revisão Q3 agendada para julho."},
    {"conv_id":"conv-paulo-20260510","client_id":"paulo","channel":"email","conv_date":"2026-05-10","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Monthly report April sent. +0.6% for the month, marginally below benchmark. Paulo acknowledges, no concerns.",
     "summary_pt":"Relatório mensal de abril enviado. +0,6% no mês, levemente abaixo do benchmark. Paulo reconhece, sem preocupações."},
    {"conv_id":"conv-paulo-20260415","client_id":"paulo","channel":"call","conv_date":"2026-04-15","duration_s":1320,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Paulo asks about increasing monthly DCA from R$5k to R$8k. Advisor models: target date improves by 2 years. Paulo confirms R$7k starting June.",
     "summary_pt":"Paulo pergunta sobre aumentar DCA mensal de R$5k para R$8k. Assessor projeta: prazo para a meta melhora 2 anos. Paulo confirma R$7k a partir de junho."},

    # ── TEREZA BITTENCOURT ────────────────────────────────────────────────────
    {"conv_id":"conv-tereza-20260615","client_id":"tereza","channel":"whatsapp","conv_date":"2026-06-15","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Monthly check-in. Portfolio +0.7% for June so far. Tereza happy with income-focused approach.",
     "summary_pt":"Check-in mensal. Carteira +0,7% em junho até agora. Tereza satisfeita com a abordagem focada em renda."},
    {"conv_id":"conv-tereza-20260602","client_id":"tereza","channel":"email","conv_date":"2026-06-02","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"May report: +0.5%, slight underperformance vs CDI+0.2pp. Advisor explains short-term duration impact. No action needed.",
     "summary_pt":"Relatório de maio: +0,5%, leve underperformance vs CDI+0,2pp. Assessor explica impacto de duration de curto prazo. Sem ação necessária."},
    {"conv_id":"conv-tereza-20260520","client_id":"tereza","channel":"call","conv_date":"2026-05-20","duration_s":2700,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Tereza's daughter starting university in 2028. Wants to plan a R$200k education reserve. Advisor proposes a dedicated fixed income ladder.",
     "summary_pt":"Filha de Tereza começando universidade em 2028. Quer planejar reserva de R$200k para educação. Assessor propõe escadinha de renda fixa dedicada."},
    {"conv_id":"conv-tereza-20260510","client_id":"tereza","channel":"email","conv_date":"2026-05-10","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Annual review. Portfolio at R$6.7M, +3.8% YTD. Well-positioned. No major changes. Next review October 2026.",
     "summary_pt":"Revisão anual. Carteira em R$6,7M, +3,8% no ano. Bem posicionada. Sem grandes mudanças. Próxima revisão em outubro de 2026."},
    {"conv_id":"conv-tereza-20260420","client_id":"tereza","channel":"whatsapp","conv_date":"2026-04-20","duration_s":None,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Tereza asks about maturity dates for Tesouro IPCA positions. Advisor sends summary: tranches maturing in 2027, 2029, and 2033.",
     "summary_pt":"Tereza pergunta sobre vencimentos das posições em Tesouro IPCA. Assessor envia resumo: tranches com vencimento em 2027, 2029 e 2033."},

    # ── SOFIA MARQUES ─────────────────────────────────────────────────────────
    {"conv_id":"conv-sofia-20260620","client_id":"sofia","channel":"call","conv_date":"2026-06-20","duration_s":1980,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"90-day onboarding review. Portfolio at R$2.2M, conservative fixed income. Sofia very happy with the experience. Still learning the platform.",
     "summary_pt":"Revisão de onboarding de 90 dias. Carteira em R$2,2M, renda fixa conservadora. Sofia muito satisfeita com a experiência. Ainda aprendendo a plataforma."},
    {"conv_id":"conv-sofia-20260610","client_id":"sofia","channel":"whatsapp","conv_date":"2026-06-10","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Sofia asks for help interpreting her portfolio statement. Advisor explains: total value, monthly return, YTD, benchmark comparison.",
     "summary_pt":"Sofia pede ajuda para interpretar seu extrato de carteira. Assessor explica: valor total, retorno mensal, no ano e comparação com benchmark."},
    {"conv_id":"conv-sofia-20260528","client_id":"sofia","channel":"email","conv_date":"2026-05-28","duration_s":None,"sentiment":"neutral","has_audio":False,"audio_file":None,
     "summary_en":"Formal onboarding completion. All documents signed, suitability completed (conservative), investment policy agreed. Welcome package sent.",
     "summary_pt":"Conclusão formal do onboarding. Todos os documentos assinados, suitability concluído (conservador), política de investimentos acordada. Kit de boas-vindas enviado."},
    {"conv_id":"conv-sofia-20260515","client_id":"sofia","channel":"call","conv_date":"2026-05-15","duration_s":2700,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"60-day check-in. +1.8% since inception. Sofia comfortable with conservative approach. Advisor notes she may consider moderate profile in 12 months.",
     "summary_pt":"Check-in de 60 dias. +1,8% desde o início. Sofia confortável com abordagem conservadora. Assessor observa que pode considerar perfil moderado em 12 meses."},
    {"conv_id":"conv-sofia-20260320","client_id":"sofia","channel":"call","conv_date":"2026-03-20","duration_s":3600,"sentiment":"positive","has_audio":False,"audio_file":None,
     "summary_en":"Initial onboarding call. Sofia referred by a colleague. Transferred R$2.2M from another bank. Goals: capital preservation, income, retirement in 15 years. Conservative profile confirmed.",
     "summary_pt":"Ligação inicial de onboarding. Sofia indicada por colega. Transferiu R$2,2M de outro banco. Objetivos: preservação de capital, renda, aposentadoria em 15 anos. Perfil conservador confirmado."},
]

# ── TURNS ─────────────────────────────────────────────────────────────────────
# Full dialog for Ricardo Jun 14 (call with audio) and Otávio Jun 9 (call with audio)
# Other calls have abbreviated turns (summary-level). WhatsApp/email have 2-4 message turns.

TURNS = [
    # ── Ricardo Jun 14 — full dialog ──────────────────────────────────────────
    {"turn_id":"t-ric-614-1","conv_id":"conv-ricardo-20260614","speaker":"advisor","turn_order":1,
     "text_pt":"Oi Ricardo, bom dia. Obrigado por atender. Vi aqui que sua posição em renda variável subiu para 71% com o movimento de ontem. Queria entender como você está se sentindo sobre isso.",
     "text_en":"Hi Ricardo, good morning. Thanks for picking up. I can see your equity position climbed to 71% after yesterday's move. I wanted to understand how you're feeling about that."},
    {"turn_id":"t-ric-614-2","conv_id":"conv-ricardo-20260614","speaker":"client","turn_order":2,
     "text_pt":"Pois é, tô vendo aqui. Tô bem preocupado. Com o bebê chegando em setembro, não tô confortável com esse nível de exposição.",
     "text_en":"Yeah, I can see it here. I'm really worried. With the baby arriving in September, I'm not comfortable with this level of exposure."},
    {"turn_id":"t-ric-614-3","conv_id":"conv-ricardo-20260614","speaker":"advisor","turn_order":3,
     "text_pt":"Entendo completamente, Ricardo. Essa sensação faz todo sentido num momento de transição de vida. Me conta: o que te preocupa mais — a queda do mercado de curto prazo, o tamanho total da posição, ou a reserva de emergência?",
     "text_en":"I completely understand, Ricardo. That feeling makes total sense in a life transition. Tell me — what worries you most: the short-term market drop, the total size of the position, or the emergency reserve?"},
    {"turn_id":"t-ric-614-4","conv_id":"conv-ricardo-20260614","speaker":"client","turn_order":4,
     "text_pt":"É tudo junto, mas a reserva é o que me tira o sono. Hoje tenho uns 4 meses. Com criança chegando, quero pelo menos 12.",
     "text_en":"It's all of it, but the reserve is what keeps me up at night. Right now I have about 4 months. With a baby coming, I want at least 12."},
    {"turn_id":"t-ric-614-5","conv_id":"conv-ricardo-20260614","speaker":"advisor","turn_order":5,
     "text_pt":"Certo. Então a proposta que tenho pra você equilibra as duas coisas. Reduzimos sua renda variável de 71% para 55% — ainda uma posição relevante mas bem mais confortável — e usamos os 16 pontos percentuais para montar uma reserva de emergência sólida em Tesouro Selic, líquida a qualquer momento.",
     "text_en":"Right. So the proposal I have for you balances both things. We reduce your equity from 71% to 55% — still a meaningful position but much more comfortable — and we use those 16 percentage points to build a solid emergency reserve in Tesouro Selic, liquid at any time."},
    {"turn_id":"t-ric-614-6","conv_id":"conv-ricardo-20260614","speaker":"client","turn_order":6,
     "text_pt":"Quanto isso representa em reais saindo da bolsa?",
     "text_en":"How much does that represent in reais coming out of equities?"},
    {"turn_id":"t-ric-614-7","conv_id":"conv-ricardo-20260614","speaker":"advisor","turn_order":7,
     "text_pt":"Com seu patrimônio de R$ 12,8 milhões, você passaria de aproximadamente R$ 9 milhões em ações para R$ 7 milhões. A reserva ficaria em torno de R$ 770 mil — cobrindo seus 12 meses tranquilamente.",
     "text_en":"With your R$12.8M portfolio, you'd go from approximately R$9M in equities to R$7M. The reserve would be around R$770k — comfortably covering your 12 months."},
    {"turn_id":"t-ric-614-8","conv_id":"conv-ricardo-20260614","speaker":"client","turn_order":8,
     "text_pt":"Isso me deixa bem mais confortável. E a execução — como funciona?",
     "text_en":"That makes me feel much better. And the execution — how does that work?"},
    {"turn_id":"t-ric-614-9","conv_id":"conv-ricardo-20260614","speaker":"advisor","turn_order":9,
     "text_pt":"Faço o plano de execução hoje ainda e mando pra você antes das três da tarde. Sugiro fazer em tranches ao longo de 2 semanas pra não pressionar o mercado. Você aprova cada movimento antes de executar.",
     "text_en":"I'll put the execution plan together today and send it to you before 3pm. I suggest doing it in tranches over 2 weeks so we don't pressure the market. You approve each move before it executes."},
    {"turn_id":"t-ric-614-10","conv_id":"conv-ricardo-20260614","speaker":"client","turn_order":10,
     "text_pt":"Perfeito. Pode mandar. Obrigado como sempre.",
     "text_en":"Perfect. Go ahead and send it. Thanks as always."},
    {"turn_id":"t-ric-614-11","conv_id":"conv-ricardo-20260614","speaker":"advisor","turn_order":11,
     "text_pt":"Fica tranquilo. Cuida bem da família. Até mais, Ricardo.",
     "text_en":"Take it easy. Take good care of your family. Talk soon, Ricardo."},

    # ── Ricardo Jun 9 — WhatsApp ──────────────────────────────────────────────
    {"turn_id":"t-ric-609-1","conv_id":"conv-ricardo-20260609","speaker":"client","turn_order":1,
     "text_pt":"Bom dia! Tá vendo essa queda do Ibovespa? -1,8% já de manhã. Preocupado aqui.",
     "text_en":"Good morning! Are you seeing this Ibovespa drop? -1.8% already this morning. Worried here."},
    {"turn_id":"t-ric-609-2","conv_id":"conv-ricardo-20260609","speaker":"advisor","turn_order":2,
     "text_pt":"Oi Ricardo! Vi sim. Respira — sua carteira tem um buffer de segurança justamente para absorver esses movimentos. Você não está na margem. Vamos conversar com calma na call de quinta.",
     "text_en":"Hi Ricardo! I saw it. Take a breath — your portfolio has a safety buffer specifically to absorb these moves. You're not on the edge. Let's talk calmly on Thursday's call."},
    {"turn_id":"t-ric-609-3","conv_id":"conv-ricardo-20260609","speaker":"client","turn_order":3,
     "text_pt":"Tá bom. Quinta às 9h ainda é?",
     "text_en":"Ok. Thursday at 9am still on?"},
    {"turn_id":"t-ric-609-4","conv_id":"conv-ricardo-20260609","speaker":"advisor","turn_order":4,
     "text_pt":"Confirmado! Tenho novidades sobre seu perfil pra discutir também.",
     "text_en":"Confirmed! I have some news on your profile to discuss too."},

    # ── Ricardo May 28 — call (abbreviated) ───────────────────────────────────
    {"turn_id":"t-ric-528-1","conv_id":"conv-ricardo-20260528","speaker":"advisor","turn_order":1,
     "text_pt":"Ricardo, sua carteira tá em +2,3% no ano. Está dentro do esperado.",
     "text_en":"Ricardo, your portfolio is at +2.3% YTD. It's within expectations."},
    {"turn_id":"t-ric-528-2","conv_id":"conv-ricardo-20260528","speaker":"client","turn_order":2,
     "text_pt":"Tá bom. Olha, o bebê vai chegar em setembro. Acho que a gente vai precisar revisar o plano.",
     "text_en":"Ok. Look, the baby is arriving in September. I think we'll need to revisit the plan."},
    {"turn_id":"t-ric-528-3","conv_id":"conv-ricardo-20260528","speaker":"advisor","turn_order":3,
     "text_pt":"Importante você falar isso. Vamos agendar uma conversa específica sobre isso. Anoto aqui.",
     "text_en":"Important that you're bringing this up. Let's schedule a specific conversation about that. I'll note it here."},

    # ── Otávio Jun 9 — full dialog ────────────────────────────────────────────
    {"turn_id":"t-ota-609-1","conv_id":"conv-otavio-20260609","speaker":"advisor","turn_order":1,
     "text_pt":"Otávio! Boa tarde, tudo bem? Vi que o aporte de julho tá confirmado — R$ 500 mil é isso?",
     "text_en":"Otávio! Good afternoon, all good? I see the July inflow is confirmed — R$500k, right?"},
    {"turn_id":"t-ota-609-2","conv_id":"conv-otavio-20260609","speaker":"client","turn_order":2,
     "text_pt":"Isso mesmo, dia 15 de julho. Tava querendo conversar justamente sobre onde alocar bem esse dinheiro.",
     "text_en":"That's right, July 15th. I was actually wanting to talk about where to put this money well."},
    {"turn_id":"t-ota-609-3","conv_id":"conv-otavio-20260609","speaker":"advisor","turn_order":3,
     "text_pt":"Perfeito. Já preparei uma proposta alinhada com seu perfil. Com o cenário de mercado atual, pensaria em três blocos: 50% em renda variável — uma combinação de ETF de Ibovespa e tech — 30% num fundo de crédito de infraestrutura que acabou de abrir, com retorno projetado de CDI mais 3,2%, e 20% em multimercado para dar flexibilidade.",
     "text_en":"Perfect. I've already prepared a proposal aligned with your profile. Given the current market environment, I'd think in three blocks: 50% in equities — a mix of Ibovespa ETF and tech — 30% in an infrastructure credit fund that just opened, with projected returns of CDI plus 3.2%, and 20% in multimarket for flexibility."},
    {"turn_id":"t-ota-609-4","conv_id":"conv-otavio-20260609","speaker":"client","turn_order":4,
     "text_pt":"CDI mais 3,2% nesse fundo de infraestrutura — isso é bem interessante. A janela fecha quando?",
     "text_en":"CDI plus 3.2% on that infrastructure fund — that's quite interesting. When does the window close?"},
    {"turn_id":"t-ota-609-5","conv_id":"conv-otavio-20260609","speaker":"advisor","turn_order":5,
     "text_pt":"Fecha dia 30 de junho. Sendo um dos primeiros cotistas você entra no melhor patamar de entrada. Você tem posição em caixa hoje se quiser entrar antes do aporte de julho?",
     "text_en":"It closes June 30th. Being one of the first investors, you'd get the best entry price. Do you have cash today if you want to enter before the July inflow?"},
    {"turn_id":"t-ota-609-6","conv_id":"conv-otavio-20260609","speaker":"client","turn_order":6,
     "text_pt":"Tenho uns R$ 80 mil parados. Mas prefiro esperar o aporte pra entrar com o volume maior. Vale a pena?",
     "text_en":"I have about R$80k idle. But I'd rather wait for the inflow to go in with bigger volume. Is it worth it?"},
    {"turn_id":"t-ota-609-7","conv_id":"conv-otavio-20260609","speaker":"advisor","turn_order":7,
     "text_pt":"Vale sim. O fundo tem captação mínima de R$ 50 mil, então você já teria acesso com os 80k. Mas se preferir esperar, ainda dá tempo — a janela vai até 30 de junho e você confirma semana que vem.",
     "text_en":"Absolutely worth it. The fund has a minimum of R$50k, so you'd already have access with the 80k. But if you prefer to wait, there's still time — the window runs until June 30 and you can confirm next week."},
    {"turn_id":"t-ota-609-8","conv_id":"conv-otavio-20260609","speaker":"client","turn_order":8,
     "text_pt":"Então manda o plano por escrito que eu assino semana que vem. Ficou bem estruturado.",
     "text_en":"Then send the written plan and I'll sign off next week. It's well structured."},
    {"turn_id":"t-ota-609-9","conv_id":"conv-otavio-20260609","speaker":"advisor","turn_order":9,
     "text_pt":"Mando ainda hoje. Qualquer dúvida me chama no WhatsApp. Abraço, Otávio.",
     "text_en":"I'll send it today. Any questions, message me on WhatsApp. Take care, Otávio."},
    {"turn_id":"t-ota-609-10","conv_id":"conv-otavio-20260609","speaker":"client","turn_order":10,
     "text_pt":"Combinado! Obrigado.",
     "text_en":"Deal! Thanks."},

    # ── Fernando Jun 10 — call (abbreviated) ─────────────────────────────────
    {"turn_id":"t-fer-610-1","conv_id":"conv-fernando-20260610","speaker":"advisor","turn_order":1,
     "text_pt":"Fernando, sua posição em RV subiu para 71% — acima da banda acordada de 60%. Precisamos conversar sobre isso.",
     "text_en":"Fernando, your equity position rose to 71% — above the agreed 60% band. We need to talk about this."},
    {"turn_id":"t-fer-610-2","conv_id":"conv-fernando-20260610","speaker":"client","turn_order":2,
     "text_pt":"Eu sei, mas tá performando bem. Não vejo razão pra reduzir agora.",
     "text_en":"I know, but it's performing well. I don't see a reason to reduce now."},
    {"turn_id":"t-fer-610-3","conv_id":"conv-fernando-20260610","speaker":"advisor","turn_order":3,
     "text_pt":"Entendo a lógica, mas temos uma obrigação regulatória de operar dentro da política. Vou documentar essa conversa formalmente.",
     "text_en":"I understand the logic, but we have a regulatory obligation to operate within the policy. I'll document this conversation formally."},

    # ── Helena Jun 12 — WhatsApp ──────────────────────────────────────────────
    {"turn_id":"t-hel-612-1","conv_id":"conv-helena-20260612","speaker":"advisor","turn_order":1,
     "text_pt":"Oi Helena, já deu uma olhada na proposta de realocação que enviei?",
     "text_en":"Hi Helena, have you had a chance to look at the reallocation proposal I sent?"},
    {"turn_id":"t-hel-612-2","conv_id":"conv-helena-20260612","speaker":"client","turn_order":2,
     "text_pt":"Tô revisando sim. Parece interessante. Te dou uma resposta até sexta.",
     "text_en":"I'm reviewing it yes. Looks interesting. I'll give you an answer by Friday."},
    {"turn_id":"t-hel-612-3","conv_id":"conv-helena-20260612","speaker":"advisor","turn_order":3,
     "text_pt":"Perfeito! Qualquer dúvida pode me chamar aqui.",
     "text_en":"Perfect! Any questions, feel free to reach out here."},

    # ── Lúcia Jun 8 — WhatsApp ────────────────────────────────────────────────
    {"turn_id":"t-luc-608-1","conv_id":"conv-lucia-20260608","speaker":"client","turn_order":1,
     "text_pt":"Acabei de ver o extrato de maio — amei os resultados 😍 +0,9% no mês!",
     "text_en":"Just saw the May statement — loving the results 😍 +0.9% for the month!"},
    {"turn_id":"t-luc-608-2","conv_id":"conv-lucia-20260608","speaker":"advisor","turn_order":2,
     "text_pt":"Que ótimo, Lúcia! Você está arrasando. E aliás — seu aniversário é essa semana! 🎉",
     "text_en":"Wonderful, Lúcia! You're killing it. And by the way — your birthday is this week! 🎉"},
    {"turn_id":"t-luc-608-3","conv_id":"conv-lucia-20260608","speaker":"client","turn_order":3,
     "text_pt":"É sim! Obrigada! Bora um café pra conversar sobre aquela ideia de previdência?",
     "text_en":"It is! Thank you! Want to grab a coffee and talk about that pension idea?"},
    {"turn_id":"t-luc-608-4","conv_id":"conv-lucia-20260608","speaker":"advisor","turn_order":4,
     "text_pt":"Adoraria! Te mando convite de agenda hoje.",
     "text_en":"I'd love that! I'll send you a calendar invite today."},

    # ── Beatriz Jun 11 — email (abbreviated) ─────────────────────────────────
    {"turn_id":"t-bea-611-1","conv_id":"conv-beatriz-20260611","speaker":"advisor","turn_order":1,
     "text_pt":"Beatriz, seu questionário de suitability vence em 30 de junho. Precisamos agendar a renovação antes disso para manter sua carteira operacional.",
     "text_en":"Beatriz, your suitability assessment expires on June 30. We need to schedule the renewal before then to keep your portfolio operational."},
    {"turn_id":"t-bea-611-2","conv_id":"conv-beatriz-20260611","speaker":"client","turn_order":2,
     "text_pt":"Entendi. Estou na época de provas mas vou ver um horário. Pode ser na semana do dia 22?",
     "text_en":"I understand. I'm in exam period but I'll find a time. Can it be the week of the 22nd?"},

    # ── Otávio Jun 2 — WhatsApp ───────────────────────────────────────────────
    {"turn_id":"t-ota-602-1","conv_id":"conv-otavio-20260602","speaker":"client","turn_order":1,
     "text_pt":"Confirmado! R$500k dia 15 de julho. Fundo de infra ainda tá aberto até 30 de junho né?",
     "text_en":"Confirmed! R$500k on July 15. The infra fund is still open until June 30, right?"},
    {"turn_id":"t-ota-602-2","conv_id":"conv-otavio-20260602","speaker":"advisor","turn_order":2,
     "text_pt":"Sim! Janela aberta até 30 de junho. Ainda dá tempo de entrar com o aporte de julho.",
     "text_en":"Yes! Window open until June 30. Still time to enter with the July inflow."},

    # ── Camila Jun 9 — WhatsApp ───────────────────────────────────────────────
    {"turn_id":"t-cam-609-1","conv_id":"conv-camila-20260609","speaker":"client","turn_order":1,
     "text_pt":"Ainda tô pensando na migração do VGBL pro PGBL. Conversei com meu contador, ele achou interessante mas quer ver os números.",
     "text_en":"Still thinking about migrating from VGBL to PGBL. Talked to my accountant, he found it interesting but wants to see the numbers."},
    {"turn_id":"t-cam-609-2","conv_id":"conv-camila-20260609","speaker":"advisor","turn_order":2,
     "text_pt":"Ótimo! Posso mandar uma análise detalhada pra ele também se quiser. Só precisamos decidir antes do fim do ano para aproveitar a dedução de 2026.",
     "text_en":"Great! I can send him a detailed analysis too if you'd like. We just need to decide before year-end to use the 2026 deduction."},

    # ── André Jun 13 — call (abbreviated) ────────────────────────────────────
    {"turn_id":"t-and-613-1","conv_id":"conv-andre-20260613","speaker":"advisor","turn_order":1,
     "text_pt":"André, sua RV tá em 62%, 2 pontos acima da banda máxima. Precisamos agir.",
     "text_en":"André, your equity is at 62%, 2 points above the policy ceiling. We need to act."},
    {"turn_id":"t-and-613-2","conv_id":"conv-andre-20260613","speaker":"client","turn_order":2,
     "text_pt":"Sei disso. Mas o mercado tá caindo, não faz sentido vender agora. Deixa eu esperar uma recuperação.",
     "text_en":"I know. But the market is falling, it doesn't make sense to sell now. Let me wait for a recovery."},
    {"turn_id":"t-and-613-3","conv_id":"conv-andre-20260613","speaker":"advisor","turn_order":3,
     "text_pt":"Entendo, mas preciso documentar que você foi informado. Vou enviar um comunicado formal agora.",
     "text_en":"I understand, but I need to document that you were informed. I'll send a formal notice now."},

    # ── Gustavo Jun 13 — call (abbreviated) ──────────────────────────────────
    {"turn_id":"t-gus-613-1","conv_id":"conv-gustavo-20260613","speaker":"client","turn_order":1,
     "text_pt":"O comitê rejeitou a proposta de rebalanceamento de novo. Disseram que não é o momento certo dado o cenário macro.",
     "text_en":"The committee rejected the rebalancing proposal again. They said it's not the right time given the macro environment."},
    {"turn_id":"t-gus-613-2","conv_id":"conv-gustavo-20260613","speaker":"advisor","turn_order":2,
     "text_pt":"Entendo. Vamos tentar a alternativa abaixo de R$1M que não precisa de voto pleno. Posso preparar uma nova proposta essa semana.",
     "text_en":"I understand. Let's try the sub-R$1M alternative that doesn't require a full vote. I can prepare a new proposal this week."},
    {"turn_id":"t-gus-613-3","conv_id":"conv-gustavo-20260613","speaker":"client","turn_order":3,
     "text_pt":"Faz isso. Precisa resolver logo.",
     "text_en":"Do that. It needs to be resolved soon."},
]
